version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./raw:/usr/share/nginx/html
      - ./docker_files/conf.d/raw_javascript.conf:/etc/nginx/conf.d/raw_javascript.conf